name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: agg_files
            asset_name: agg_files-linux-x86_64
          - os: macos-latest
            artifact_name: agg_files
            asset_name: agg_files-darwin-x86_64
          - os: windows-latest
            artifact_name: agg_files.exe
            asset_name: agg_files-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ./agg_files
        run: cargo build --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: agg_files/target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
